name: Build pdfs.json
on:
  push:
    branches: [ main ]
  workflow_dispatch: {}
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate manifest
        run: |
          python - <<'PY'
          import os, json
          out = []
          for root, _, files in os.walk('.'):
            for f in files:
              if f.lower().endswith('.pdf'):
                p = os.path.join(root, f).replace('./','')
                out.append({'href': p, 'name': f})
          out.sort(key=lambda x: x['name'])
          with open('pdfs.json','w',encoding='utf-8') as fh:
            json.dump(out, fh, ensure_ascii=False, indent=2)
          PY
      - name: Commit manifest
        run: |
          if [ -n "$(git status --porcelain pdfs.json)" ]; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add pdfs.json
            git commit -m "Update pdfs.json"
            git push
          else
            echo "No changes"
          fi
